[package]
name = "weather"
version = "0.1.0"
edition = "2021"
author = "Andrii D"
description = "Weather CLI application for Windows/Linux/macOS"

[dependencies]
clap = { version = "3.1.9", features = ["derive", "cargo"] }
log = "0.4.16"